@startuml
autonumber
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam ParticipantPadding 50
hide footbox

title Send data by request from user

actor User
participant "Source\nEntity" as e1
collections "Target\nEntities" as e2

User -> e1 : Perform operation
rnote over e1
 Sends personal data
 on behalf of the user
 Needs consent for
 all targets
endrnote
e1 -> e2 : Send data

@enduml