@startuml
autonumber
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam ParticipantPadding 50

title Flow with consent from user

actor User
participant "Source\nEntity" as e1
collections "Target\nEntities" as e2

User -> e2 : Consent to access my data
e2 -> e1 : Get data (with user consent)
rnote over e1
 Check consent of User
 for each entity
 accessing the data
endrnote
activate e1
e1 --> e2 : Return data
deactivate e1

@enduml