@startuml
autonumber
skinparam sequenceArrowThickness 2
skinparam roundcorner 10
skinparam ParticipantPadding 50
hide footbox

title Via the user with W3C Credentials

actor User
participant "Source\nEntity" as e1
collections "Target\nEntities" as e2

e1 -> User : Credential (W3C)
rnote over User
 User stores Credentials
 and sends them
 without involvement
 from source Entity
endrnote

User -> e2 : Presentation (of Credential)

@enduml